### ISSUE TITLE
Cannot run the app via activator

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#1]
Running `activator run` boots up the server side correctly, however, the appgen app fails as webpack dev server is not running.

**Comment by tobice** [comment]
This is a matter of missing documentation. 

`activator run` runs the app in dev mode for which you need to run the webpack dev server manually with `npm run appgen-dev`.

For production mode, use `activator start`, or `activator dist` to create a standalone package. The JavaScripts should be compiled automatically into a bundle which is then served as a static file.

**Comment by jirihelmich** [comment]
I guess it could start the webpack dev server as well? Or is there any advantage in starting it manually?

**Comment by tobice** [comment]
Well, mixing Scala compiler and webpack compiler error messages in a single output didn't seem like a good idea. I prefer running them separately in two separated consoles. Another advantage is that both compilers are inclined to crash occasionally. It's better if they crash independent on each other rather than one taking down the other.

**Comment by jirihelmich** [comment]
OK, sounds reasonable. At least, it could write something into console, like

"You need to run `webpack ... ... ...` ... "

So that it's possible for the developer to just copy-paste it into another terminal window.

**Comment by tobice** [comment]
Good idea.

**Comment by tobice** [comment]
I managed to get the message printed at the beginning of the console output for `activator run` which means that it's kind of easy to miss. 

I'm not that familiar with the sbt build process (especially with the task hierarchy) so I wasn't able to get it printed in a more useful moment (ideally just after `Server started, use Ctrl+D to stop and go back to the console...`).

This might be of help (in case somebody decides to look into it again):
http://eng.kifi.com/hooking-in-to-play-frameworks-sbt-plugin-lifecycle/
