### ISSUE TITLE
Map visualizer - Invisible arrow

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#10]
![image](https://cloud.githubusercontent.com/assets/174768/15140321/d9ad7150-169a-11e6-97fe-b9cf7f65f9dc.png)

The arrow is not visible -> it's not clear that you can click the header to expand the panel.

**Comment by tobice** [comment]
720e9fe also fixes the problem that clicking the arrow icon usually failed to collapse/expand the panel. Also the used icons are now unified with those used for individual filter collapsing/expanding.
