### ISSUE TITLE
Map visualizer - Remove the "refresh on startup" feature

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#11]

**Comment by tobice** [comment]
Why? What should be the behavior then? Should the markers be displayed automatically always or never?

I'm closing this for now. My reasoning is that both approaches make sense in different scenarios. For completely static applications (hidden filters) it is necessary that the markers are loaded automatically. For applications that would visualize potentially very large number of markers (e.g. CTIA Checks), causing performance problems on the client side, I think it's a good idea that the user has to explicitly click a button to _kill his browser_.
