### ISSUE TITLE
App speed

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#13]
![image](https://cloud.githubusercontent.com/assets/174768/15140678/889a9b88-169c-11e6-8fde-80db373cd259.png)

When in the map app (pre-generated), you still load all the skos concepts and schemes, no matter if they are really used or not.

I have 1 scheme and 2 concepts active and I wait for 3 minutes for the app to display 2 markers (I cleared the cache to see the behaviour). We can rely on the cache, but the queries needs to be "optimized" for the worst case - cold app start, no in-memory cache available.

**Comment by tobice** [comment]
![maps-visualizer-requests](https://cloud.githubusercontent.com/assets/5073664/15293557/d34ffb3c-1b88-11e6-9deb-e8b2bcfb23b1.png)

As we talked about it today, I looked into what's taking so long. Apparently, it's the first request which fetches the properties ([`GeoPropertiesQuery`](https://github.com/tobice/LDVMi/blob/master/src/app/model/rdf/sparql/geo/query/GeoPropertiesQuery.scala)). This requests returns two entities (500 bytes of data).

I could pull out URIs of selected properties from the application config and make a specified query asking directly for those resources (or one, if the rest is disabled) which should be faster.

Nevertheless, before implementing it (which would not be that easy) I would start with two other simpler approaches:
1. The discussed disk cache. It would achieve the same result but it would be a universal re-usable speed boost for the whole platform.
2. I would check why this single query returning so little data takes so long. We can't avoid it anyway, it has to be run at least once after when the app is created and it would make sense to speed up that process.

Both of these ways would require almost minimal changes in the visualizer's codebase.

**Comment by tobice** [comment]
I implemented the aforementioned cache in 0eb3a01. The cache is disk persistent (it's stored directly in the H2 database) which means that it survives crashes. The  [`GeoPropertiesQuery`](https://github.com/tobice/LDVMi/blob/master/src/app/model/rdf/sparql/geo/query/GeoPropertiesQuery.scala) which takes so long will therefore be run only once.

I admit that there is a potential for optimizations (as suggested in the original comment), e.g. I could fetch only those resources that I need. However, all other related SPARQL queries are really fast (and cached anyway). The speed bottleneck is currently more on the client side (rendering ~300 skos concepts in React is rather slow). I'm closing this issue for now.
