### ISSUE TITLE
Prepare a list of samples

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#14]
LDVMi has now on its homepage a list of pre-defined data sources to guide the user towards a successful discovery. You might want to do the same.

**Comment by tobice** [comment]
I implemented an install script that imports all LDVM components and data sets necessary for reproducing any example mentioned in the thesis text. The process of generating a sample application is not as smooth as in the case of LDVMi but the user cannot make a wrong step along the way, i.e., he will always get to a working application.
