### ISSUE TITLE
Running a pipeline

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#15]
When a pipeline is running, the Close button is active. What happens if I close it? Can I go back to the execution and use the results?

**Comment by jirihelmich** [comment]
When the execution is done, I should somehow know. The Run pipeline button is present again. It took several minutes and I don't know if it failed or succeed. Well, I know, because the Create App is now green, but should it be the only way of displaying that?

**Comment by tobice** [comment]
The user can return to any of his discoveries through the Dashboard. That includes the evaluations as well, i.e., if an evaluation takes an hour, the user can freely close the window (even the browser), come an hour later, open the discovery and see if the evaluation has finished or not. The only problem is when the discovery (or evaluation) crashes without indicating it in the database. Then the discovery (or evaluation) appears as in progress but it's been long dead. 

In 02e5cf9 I improved the visuals of the pipeline table. There is an animated loading circle showed when the evaluation is in progress. If the evaluation succeeds, a green check icon is displayed, if it fails, a red icon is displayed. I hope it is more apparent now. 

![pipelines](https://cloud.githubusercontent.com/assets/5073664/17110853/39c87d24-529f-11e6-9476-9d4c6ddcb0be.png)
