### ISSUE TITLE
Skip listing of pipelines when only one is available

### ISSUE THREAD

**Issue by jirihelmich** [tobice/payola-viz#5]
It's an unnecessary step for the user, the listing itself is not very nice. If possible, avoid it.

**Comment by tobice** [comment]
Given how the UI works at this moment (pipelines are grouped by visualizers), it is not really possible.

Personally, I'm not overly fond of the current approach in LinkedPipes Visualization. I prefer to manually check the list of discovered pipelines before running any of them (even if there is only one). But I understand that there are situations for which it makes sense.

Ideally, both approaches should be possible, i.e., something like a "manual mode" (which is how it works now in appgen), and a "feeling luck mode" (current solution in LinkedPipes Visualization. Btw. I don't see any difference between clicking "Feeling lucky" and "Visualize").

At least I tried to make the listing more visually appealing.
